///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Processes;
using SDK.Utils;
using SDK.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class GetInfoProcessRequest
{
    [JsonProperty("appId")]
    public string AppId { get; set; }
    
    [JsonProperty("processId")]
    public string ProcessId { get; set; }
    
    internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, GetInfoProcessRequest value)
    {
        if("GetInfoProcess" == operationId)
        {
            // add path params
            
            var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
            
            var processId = PathParamSerializer.Serialize("simple", false, value.ProcessId);
            var message = new HttpRequestMessage(HttpMethod.Get, $"/processes/v1/{appId}/info/{processId}");
            return message;
        }
        throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [GetInfoProcessRequest]");
    }
}
