///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Processes;
using SDK.Utils;
using SDK.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class GetRunningProcessesResponse {
    public string? ContentType { get; set; }
    
    public string? GetRunningProcesses404ApplicationJSONString { get; set; }
    
    public IEnumerable<ProcessWithRooms>? ProcessWithRooms { get; set; }
    
    public int StatusCode { get; set; }
    
    public HttpResponseMessage? RawResponse { get; set; }
    
}
