
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace hathora
{
    using System;
    using System.Threading.Tasks;
    using System.Collections.Generic;
    using System.Text;
    using hathora.Apps;
    using hathora.Auth;
    using hathora.Builds;
    using hathora.Deployment;
    using hathora.Discovery;
    using hathora.Lobby;
    using hathora.Logs;
    using hathora.Metrics;
    using hathora.Processes;
    using hathora.Rooms;
    using System.Net.Http;
    using hathora.Utils;

    public interface IHathoraSDK
    {
        public IAppsSDK Apps { get; }
        public IAuthSDK Auth { get; }
        public IBuildsSDK Builds { get; }
        public IDeploymentSDK Deployment { get; }
        public IDiscoverySDK Discovery { get; }
        public ILobbySDK Lobby { get; }
        public ILogsSDK Logs { get; }
        public IMetricsSDK Metrics { get; }
        public IProcessesSDK Processes { get; }
        public IRoomsSDK Rooms { get; }
    }

    public class HathoraSDK: IHathoraSDK
    {
        public static List<string> ServerList = new List<string>()
        {
            "https://api.hathora.dev",
            "/",
        };

        private const string language = "csharp";
        private const string sdkVersion = "0.0.1";
        private const string sdkGenVersion = "internal";
        public Uri ServerUrl { get { return _defaultClient.BaseAddress; } }
        private HttpClient _defaultClient;
        private HttpClient _securityClient;
        public IAppsSDK Apps { get; private set; }
        public IAuthSDK Auth { get; private set; }
        public IBuildsSDK Builds { get; private set; }
        public IDeploymentSDK Deployment { get; private set; }
        public IDiscoverySDK Discovery { get; private set; }
        public ILobbySDK Lobby { get; private set; }
        public ILogsSDK Logs { get; private set; }
        public IMetricsSDK Metrics { get; private set; }
        public IProcessesSDK Processes { get; private set; }
        public IRoomsSDK Rooms { get; private set; }

        public HathoraSDK(HttpClient? client = null, string? serverUrl = null)
        {
            _defaultClient = client;
            if(_defaultClient == null)
            {
                _defaultClient = new HttpClient();
                var _serverUrl = serverUrl ?? HathoraSDK.ServerList[0];

                _defaultClient.BaseAddress = new System.Uri(_serverUrl);
            }
            _securityClient = _defaultClient;
            Apps = new AppsSDK(_defaultClient, _securityClient);
            Auth = new AuthSDK(_defaultClient, _securityClient);
            Builds = new BuildsSDK(_defaultClient, _securityClient);
            Deployment = new DeploymentSDK(_defaultClient, _securityClient);
            Discovery = new DiscoverySDK(_defaultClient, _securityClient);
            Lobby = new LobbySDK(_defaultClient, _securityClient);
            Logs = new LogsSDK(_defaultClient, _securityClient);
            Metrics = new MetricsSDK(_defaultClient, _securityClient);
            Processes = new ProcessesSDK(_defaultClient, _securityClient);
            Rooms = new RoomsSDK(_defaultClient, _securityClient);
        }
    }
}