
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace hathora.Models.Lobby
{
    using hathora.Utils;
    using hathora.Models.Shared;
    using NodaTime;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Text;
    
public class DeprecatedV1ListActivePublicLobbiesRequest
{
    [JsonProperty("Authorization")]
    public string Authorization { get; set; }
    
    [JsonProperty("appId")]
    public string AppId { get; set; }
    
    [JsonProperty("local")]
    public bool? Local { get; set; }
    
    [JsonProperty("region")]
    public RegionEnum? Region { get; set; }
    
    internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, DeprecatedV1ListActivePublicLobbiesRequest value)
    {
        if("DeprecatedV1ListActivePublicLobbies" == operationId)
        {
            // serialize query parameters
            var queryParams = new List<string>();
                    queryParams.Add(QueryParamSerializer.Serialize("simple",false, "Authorization", "", value.Authorization));
                    queryParams.Add(QueryParamSerializer.Serialize("simple",false, "appId", "", value.AppId));
                    queryParams.Add(QueryParamSerializer.Serialize("form",true, "local", "", value.Local));
                    queryParams.Add(QueryParamSerializer.Serialize("form",true, "region", "", value.Region));

            var queryParamString = $"?{String.Join("&", queryParams)}";
            // add path params
                    
                    
                    var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                    
                    
            var message = new HttpRequestMessage(HttpMethod.Get, $"/lobby/v1/{appId}/list" + queryParamString);
            message.Headers.Add("Authorization", HeaderParamSerializer.Serialize(false, value.Authorization));
            message.Headers.Add("appId", HeaderParamSerializer.Serialize(false, value.AppId));
            message.Headers.Add("local", HeaderParamSerializer.Serialize(true, value.Local));
            message.Headers.Add("region", HeaderParamSerializer.Serialize(true, value.Region));
            return message;
        }
        throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [DeprecatedV1ListActivePublicLobbiesRequest]");
    }
}
}