///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Rooms;
using SDK.Utils;
using SDK.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class CreateRoomResponse {
    public string? ContentType { get; set; }
    
    public string? CreateRoom404ApplicationJSONString { get; set; }
    
    public string? CreateRoom500ApplicationJSONString { get; set; }
    
    public string? RoomId { get; set; }
    
    public int StatusCode { get; set; }
    
    public HttpResponseMessage? RawResponse { get; set; }
    
}
