///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Auth;
using SDK.Utils;
using SDK.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class LoginAnonymousResponse {
    public string? ContentType { get; set; }
    
    public LoginAnonymous200ApplicationJSON? LoginAnonymous200ApplicationJSONObject { get; set; }
    
    public string? LoginAnonymous404ApplicationJSONString { get; set; }
    
    public int StatusCode { get; set; }
    
    public HttpResponseMessage? RawResponse { get; set; }
    
}
