///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Auth;
using SDK.Utils;
using SDK.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class LoginGoogleResponse {
    public string? ContentType { get; set; }
    
    public LoginGoogle200ApplicationJSON? LoginGoogle200ApplicationJSONObject { get; set; }
    
    public string? LoginGoogle401ApplicationJSONString { get; set; }
    
    public string? LoginGoogle404ApplicationJSONString { get; set; }
    
    public int StatusCode { get; set; }
    
    public HttpResponseMessage? RawResponse { get; set; }
    
}
