///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Shared;
using SDK.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class ActiveConnectionInfo
{
    [JsonProperty("host")]
    public string Host { get; set; }
    
    [JsonProperty("port")]
    public float Port { get; set; }
    
    [JsonProperty("roomId")]
    public string RoomId { get; set; }
    
    [JsonProperty("status")]
    public ActiveConnectionInfoStatusEnum Status { get; set; }
    
    [JsonProperty("transportType")]
    public TransportTypeEnum TransportType { get; set; }
    
}
