///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Shared;
using SDK.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public enum BuildStatusEnum
{
    	[JsonProperty("created")]
	Created,
	[JsonProperty("running")]
	Running,
	[JsonProperty("succeeded")]
	Succeeded,
	[JsonProperty("failed")]
	Failed,
}
