///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Shared;
using SDK.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class Build
{
    [JsonProperty("appId")]
    public string AppId { get; set; }
    
    [JsonProperty("buildId")]
    public float BuildId { get; set; }
    
    [JsonProperty("createdAt")]
    public DateTime CreatedAt { get; set; }
    
    [JsonProperty("createdBy")]
    public string CreatedBy { get; set; }
    
    [JsonProperty("deletedAt")]
    public DateTime DeletedAt { get; set; }
    
    [JsonProperty("finishedAt")]
    public DateTime FinishedAt { get; set; }
    
    [JsonProperty("imageSize")]
    public float ImageSize { get; set; }
    
    [JsonProperty("regionalContainerTags")]
    public IEnumerable<BuildRegionalContainerTags> RegionalContainerTags { get; set; }
    
    [JsonProperty("startedAt")]
    public DateTime StartedAt { get; set; }
    
    [JsonProperty("status")]
    public BuildStatusEnum Status { get; set; }
    
}
