///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace hathora.Models.Shared;
using hathora.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class DeploymentConfig
{
    [JsonProperty("containerPort")]
    public float ContainerPort { get; set; }
    
    [JsonProperty("env")]
    public IEnumerable<DeploymentConfigEnv> Env { get; set; }
    
    [JsonProperty("planName")]
    public PlanNameEnum PlanName { get; set; }
    
    [JsonProperty("roomsPerProcess")]
    public float RoomsPerProcess { get; set; }
    
    [JsonProperty("transportType")]
    public TransportTypeEnum TransportType { get; set; }
    
}
