
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace hathora.Models.Shared
{
    using hathora.Utils;
    using NodaTime;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Text;
    
public class DeploymentConfig
{
    [JsonProperty("containerPort")]
    public int ContainerPort { get; set; }
    
    [JsonProperty("env")]
    public IEnumerable<DeploymentConfigEnv> Env { get; set; }
    
    [JsonProperty("planName")]
    public PlanNameEnum PlanName { get; set; }
    
    [JsonProperty("roomsPerProcess")]
    public int RoomsPerProcess { get; set; }
    
    [JsonProperty("transportType")]
    public TransportTypeEnum TransportType { get; set; }
    
}
}