///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace hathora.Models.Shared;
using hathora.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class DiscoveryResponse
{
    [JsonProperty("host")]
    public string Host { get; set; }
    
    [JsonProperty("port")]
    public float Port { get; set; }
    
    [JsonProperty("region")]
    public RegionEnum Region { get; set; }
    
}
