///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Shared;
using SDK.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public enum LobbyVisibilityEnum
{
    	[JsonProperty("private")]
	Private,
	[JsonProperty("public")]
	Public,
	[JsonProperty("local")]
	Local,
}
