
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace hathora.Models.Shared
{
    using hathora.Utils;
    using NodaTime;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Text;
    
public class Lobby
{
    [JsonProperty("appId")]
    public string AppId { get; set; }
    
    [JsonProperty("createdAt")]
    public DateTime CreatedAt { get; set; }
    
    [JsonProperty("createdBy")]
    public string CreatedBy { get; set; }
    
    [JsonProperty("initialConfig")]
    public Dictionary<string, object> InitialConfig { get; set; }
    
    [JsonProperty("local")]
    public bool Local { get; set; }
    
    [JsonProperty("region")]
    public RegionEnum Region { get; set; }
    
    [JsonProperty("roomId")]
    public string RoomId { get; set; }
    
    [JsonProperty("state")]
    public Dictionary<string, object>? State { get; set; }
    
    [JsonProperty("visibility")]
    public LobbyVisibilityEnum Visibility { get; set; }
    
}
}