///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace hathora.Models.Shared;
using hathora.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public enum MetricNameEnum
{
    	[JsonProperty("cpu")]
	Cpu,
	[JsonProperty("memory")]
	Memory,
	[JsonProperty("rate_egress")]
	RateEgress,
	[JsonProperty("total_egress")]
	TotalEgress,
}
