///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace hathora.Models.Shared;
using hathora.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class MetricsResponse
{
    [JsonProperty("cpu")]
    public IEnumerable<MetricValue>? Cpu { get; set; }
    
    [JsonProperty("memory")]
    public IEnumerable<MetricValue>? Memory { get; set; }
    
    [JsonProperty("rate_egress")]
    public IEnumerable<MetricValue>? RateEgress { get; set; }
    
    [JsonProperty("total_egress")]
    public IEnumerable<MetricValue>? TotalEgress { get; set; }
    
}
