///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Shared;
using SDK.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class MetricValue
{
    [JsonProperty("timestamp")]
    public float Timestamp { get; set; }
    
    [JsonProperty("value")]
    public float Value { get; set; }
    
}
