///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Shared;
using SDK.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class RoomAllocation
{
    [JsonProperty("processId")]
    public string ProcessId { get; set; }
    
    [JsonProperty("roomAllocationId")]
    public string RoomAllocationId { get; set; }
    
    [JsonProperty("scheduledAt")]
    public DateTime ScheduledAt { get; set; }
    
    [JsonProperty("unscheduledAt")]
    public DateTime UnscheduledAt { get; set; }
    
}
