///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Shared;
using SDK.Utils;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class RoomWithoutAllocations
{
    [JsonProperty("appId")]
    public string AppId { get; set; }
    
    [JsonProperty("currentAllocation")]
    public RoomWithoutAllocationsCurrentAllocation CurrentAllocation { get; set; }
    
    [JsonProperty("roomId")]
    public string RoomId { get; set; }
    
    [JsonProperty("status")]
    public RoomStatusEnum Status { get; set; }
    
}
