
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora.Models.Builds
{
    using Newtonsoft.Json;
    
    public class RunBuildRequestBodyFile
    {
        
        [JsonProperty("content")]
        public byte[] Content { get; set; }
        
        
        [JsonProperty("file")]
        public string File { get; set; }
        
    }
}