
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace hathora.Models.Processes
{
    using hathora.Utils;
    using hathora.Models.Shared;
    using NodaTime;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Text;
    
public class GetStoppedProcessesRequest
{
    [JsonProperty("appId")]
    public string AppId { get; set; }
    
    [JsonProperty("region")]
    public Region? Region { get; set; }
    
    internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, GetStoppedProcessesRequest value, string baseUrl)
    {
        if("GetStoppedProcesses" == operationId)
        {
            var queryParams = new List<string>();
            
            
            queryParams.Add(QueryParamSerializer.Serialize("form",true, "region", "", value.Region));
            var queryParamString = $"?{String.Join("&", queryParams)}";
            
            var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
            
            var message = new HttpRequestMessage(HttpMethod.Get, baseUrl + $"/processes/v1/{appId}/list/stopped" + queryParamString);
            return message;
        }
        throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [GetStoppedProcessesRequest]");
    }
}
}