
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace hathora.Models.Deployment
{
    using hathora.Utils;
    using hathora.Models.Shared;
    using NodaTime;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Text;
    
public class CreateDeploymentRequest
{
    [JsonProperty("DeploymentConfig")]
    public DeploymentConfig DeploymentConfig { get; set; }
    
    [JsonProperty("appId")]
    public string AppId { get; set; }
    
    [JsonProperty("buildId")]
    public float BuildId { get; set; }
    
    internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, CreateDeploymentRequest value, string baseUrl)
    {
        if("CreateDeployment" == operationId)
        {
            
            
            var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
            
            var buildId = PathParamSerializer.Serialize("simple", false, value.BuildId);
            var message = new HttpRequestMessage(HttpMethod.Post, baseUrl + $"/deployments/v1/{appId}/create/{buildId}");

            string json = JsonConvert.SerializeObject(value.DeploymentConfig);
            message.Content = new StringContent(json, Encoding.UTF8, "application/json");
            return message;
        }
        throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [CreateDeploymentRequest]");
    }
}
}