///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace hathora.Models.Metrics;
using hathora.Utils;
using hathora.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class GetMetricsResponse {
    public string? ContentType { get; set; }
    
    public string? GetMetrics404ApplicationJSONString { get; set; }
    
    public string? GetMetrics422ApplicationJSONString { get; set; }
    
    public MetricsResponse? MetricsResponse { get; set; }
    
    public int StatusCode { get; set; }
    
    public HttpResponseMessage? RawResponse { get; set; }
    
}
