///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Builds;
using SDK.Utils;
using SDK.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class RunBuildRequestBodyFile
{
    [JsonProperty("content")]
    public byte[] Content { get; set; }
    
    [JsonProperty("file")]
    public string File { get; set; }
    
}
