///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace hathora.Models.Apps;
using hathora.Utils;
using hathora.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class UpdateAppRequestBodyAuthConfiguration
{
    [JsonProperty("anonymous")]
    public Dictionary<string, object>? Anonymous { get; set; }
    
    [JsonProperty("google")]
    public UpdateAppRequestBodyAuthConfigurationGoogle? Google { get; set; }
    
    [JsonProperty("nickname")]
    public Dictionary<string, object>? Nickname { get; set; }
    
}
