///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace hathora.Models.Apps;
using hathora.Utils;
using hathora.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class UpdateAppRequestBody
{
    [JsonProperty("appName")]
    public string AppName { get; set; }
    
    [JsonProperty("authConfiguration")]
    public UpdateAppRequestBodyAuthConfiguration AuthConfiguration { get; set; }
    
}
