///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace SDK.Models.Apps;
using SDK.Utils;
using SDK.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

public class UpdateAppRequestBodyAuthConfigurationGoogle
{
    [JsonProperty("clientId")]
    public string ClientId { get; set; }
    
}
