
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace hathora.Models.Shared
{
    using hathora.Utils;
    using NodaTime;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Text;
    
public class ApplicationAuthConfiguration
{
    [JsonProperty("anonymous")]
    public RecordStringNever? Anonymous { get; set; }
    
    [JsonProperty("google")]
    public ApplicationAuthConfigurationGoogle? Google { get; set; }
    
    [JsonProperty("nickname")]
    public RecordStringNever? Nickname { get; set; }
    
}
}