
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora.Models.Shared
{
    using System;
using Newtonsoft.Json;
using Hathora.Models.Shared;
    
/// <summary>
/// Ok
/// </summary>
    public class Application
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("appName")]
        public string AppName { get; set; }
        
        
        [JsonProperty("appSecret")]
        public string AppSecret { get; set; }
        
        
        [JsonProperty("authConfiguration")]
        public ApplicationAuthConfiguration AuthConfiguration { get; set; }
        
        
        [JsonProperty("createdAt")]
        public DateTime CreatedAt { get; set; }
        
        
        [JsonProperty("createdBy")]
        public string CreatedBy { get; set; }
        
        
        [JsonProperty("deletedAt")]
        public DateTime DeletedAt { get; set; }
        
        
        [JsonProperty("deletedBy")]
        public string DeletedBy { get; set; }
        
        
        [JsonProperty("orgId")]
        public string OrgId { get; set; }
        
    }
}