
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora.Models.Shared
{
    using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Hathora.Models.Shared;
    
/// <summary>
/// Ok
/// </summary>
    public class Build
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("buildId")]
        public float BuildId { get; set; }
        
        
        [JsonProperty("createdAt")]
        public DateTime CreatedAt { get; set; }
        
        
        [JsonProperty("createdBy")]
        public string CreatedBy { get; set; }
        
        
        [JsonProperty("deletedAt")]
        public DateTime DeletedAt { get; set; }
        
        
        [JsonProperty("finishedAt")]
        public DateTime FinishedAt { get; set; }
        
        
        [JsonProperty("imageSize")]
        public float ImageSize { get; set; }
        
        
        [JsonProperty("regionalContainerTags")]
        public List<BuildRegionalContainerTags> RegionalContainerTags { get; set; }
        
        
        [JsonProperty("startedAt")]
        public DateTime StartedAt { get; set; }
        
        
        [JsonProperty("status")]
        public BuildStatus Status { get; set; }
        
    }
}