
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora.Models.Shared
{
    using System;
using Newtonsoft.Json;
using Hathora.Models.Shared;
    
/// <summary>
/// Ok
/// </summary>
    public class Lobby
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("createdAt")]
        public DateTime CreatedAt { get; set; }
        
        
        [JsonProperty("createdBy")]
        public string CreatedBy { get; set; }
        
        
        [JsonProperty("initialConfig")]
        public LobbyInitialConfig InitialConfig { get; set; }
        
        
        [JsonProperty("local")]
        public bool Local { get; set; }
        
        
        [JsonProperty("region")]
        public Region Region { get; set; }
        
        
        [JsonProperty("roomId")]
        public string RoomId { get; set; }
        
        
        [JsonProperty("state")]
        public LobbyState? State { get; set; }
        
        
        [JsonProperty("visibility")]
        public LobbyVisibility Visibility { get; set; }
        
    }
}