
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace hathora.Models.Shared
{
    using hathora.Utils;
    using NodaTime;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Text;
    
public class MetricsResponse
{
    [JsonProperty("cpu")]
    public List<MetricValue>? Cpu { get; set; }
    
    [JsonProperty("memory")]
    public List<MetricValue>? Memory { get; set; }
    
    [JsonProperty("rate_egress")]
    public List<MetricValue>? RateEgress { get; set; }
    
    [JsonProperty("total_egress")]
    public List<MetricValue>? TotalEgress { get; set; }
    
}
}