
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace hathora.Models.Shared
{
    using hathora.Utils;
    using NodaTime;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Text;
    
public enum Region
{
    	[JsonProperty("Seattle")]
	Seattle,
	[JsonProperty("Washington_DC")]
	WashingtonDC,
	[JsonProperty("Chicago")]
	Chicago,
	[JsonProperty("London")]
	London,
	[JsonProperty("Frankfurt")]
	Frankfurt,
	[JsonProperty("Mumbai")]
	Mumbai,
	[JsonProperty("Singapore")]
	Singapore,
	[JsonProperty("Tokyo")]
	Tokyo,
	[JsonProperty("Sydney")]
	Sydney,
	[JsonProperty("Sao_Paulo")]
	SaoPaulo,
}
}