
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora.Models.Shared
{
    using Newtonsoft.Json;
using Hathora.Models.Shared;
    
/// <summary>
/// From T, pick a set of properties whose keys are in the union K
/// </summary>
    public class RoomWithoutAllocations
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("currentAllocation")]
        public RoomWithoutAllocationsCurrentAllocation CurrentAllocation { get; set; }
        
        
        [JsonProperty("roomId")]
        public string RoomId { get; set; }
        
        
        [JsonProperty("status")]
        public RoomStatus Status { get; set; }
        
    }
}