
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora.Models.Shared
{
    using System;
using Newtonsoft.Json;
    
    public class RoomAllocation
    {
        
        [JsonProperty("processId")]
        public string ProcessId { get; set; }
        
        
        [JsonProperty("roomAllocationId")]
        public string RoomAllocationId { get; set; }
        
        
        [JsonProperty("scheduledAt")]
        public DateTime ScheduledAt { get; set; }
        
        
        [JsonProperty("unscheduledAt")]
        public DateTime UnscheduledAt { get; set; }
        
    }
}