
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora.Models.Auth
{
    using Newtonsoft.Json;
    
/// <summary>
/// Ok
/// </summary>
    public class LoginGoogle200ApplicationJSON
    {
        
        [JsonProperty("token")]
        public string Token { get; set; }
        
    }
}