
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora
{
    using System;
    using System.Threading.Tasks;
    using System.Collections.Generic;
    using System.Text;
    using Hathora.Apps;
    using Hathora.Auth;
    using Hathora.Builds;
    using Hathora.Deployment;
    using Hathora.Discovery;
    using Hathora.Lobby;
    using Hathora.Logs;
    using Hathora.Metrics;
    using Hathora.Processes;
    using Hathora.Rooms;
    using System.Net;
    using System.Net.Http;
    using Hathora.Utils;
    using NodaTime;

    public interface IHathoraSDK
    {
        public IAppsSDK Apps { get; }
        public IAuthSDK Auth { get; }
        public IBuildsSDK Builds { get; }
        public IDeploymentSDK Deployment { get; }
        public IDiscoverySDK Discovery { get; }
        public ILobbySDK Lobby { get; }
        public ILogsSDK Logs { get; }
        public IMetricsSDK Metrics { get; }
        public IProcessesSDK Processes { get; }
        public IRoomsSDK Rooms { get; }
    }public class SDKConfig
    {
    }

    public class HathoraSDK: IHathoraSDK
    {
        public SDKConfig Config { get; private set; }
        public static List<string> ServerList = new List<string>()
        {
            "https://api.hathora.dev",
            "/",
        };

        private const string _language = "csharp";
        private const string _sdkVersion = "0.0.1";
        private const string _sdkGenVersion = "internal";
        private const string _openapiDocVersion = "0.0.1";
        public Uri ServerUrl { get { return _defaultClient.Client.BaseAddress; } }
        private SpeakeasyHttpClient _defaultClient;
        private SpeakeasyHttpClient _securityClient;
        public IAppsSDK Apps { get; private set; }
        public IAuthSDK Auth { get; private set; }
        public IBuildsSDK Builds { get; private set; }
        public IDeploymentSDK Deployment { get; private set; }
        public IDiscoverySDK Discovery { get; private set; }
        public ILobbySDK Lobby { get; private set; }
        public ILogsSDK Logs { get; private set; }
        public IMetricsSDK Metrics { get; private set; }
        public IProcessesSDK Processes { get; private set; }
        public IRoomsSDK Rooms { get; private set; }

        public HathoraSDK(HttpClient? client = null, string? serverUrl = null)
        {
            _defaultClient = new SpeakeasyHttpClient(client);
            if(client == null)
            {
                var _serverUrl = serverUrl ?? HathoraSDK.ServerList[0];

                _defaultClient.SetBaseUrl(_serverUrl);
            }
            _securityClient = new SpeakeasyHttpClient(_defaultClient.Client);

            Config = new SDKConfig()
            {
            };
            Apps = new AppsSDK(_defaultClient, _securityClient, Config);
            Auth = new AuthSDK(_defaultClient, _securityClient, Config);
            Builds = new BuildsSDK(_defaultClient, _securityClient, Config);
            Deployment = new DeploymentSDK(_defaultClient, _securityClient, Config);
            Discovery = new DiscoverySDK(_defaultClient, _securityClient, Config);
            Lobby = new LobbySDK(_defaultClient, _securityClient, Config);
            Logs = new LogsSDK(_defaultClient, _securityClient, Config);
            Metrics = new MetricsSDK(_defaultClient, _securityClient, Config);
            Processes = new ProcessesSDK(_defaultClient, _securityClient, Config);
            Rooms = new RoomsSDK(_defaultClient, _securityClient, Config);
        }
    }
}