
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora.Models.Rooms
{
    using System.Net.Http;
    
    public class GetConnectionInfoResponse {
    /// <summary>
    /// Ok
    /// </summary>
        public object? ConnectionInfo { get; set; }
        
        public string? ContentType { get; set; }
        
        public string? GetConnectionInfo400ApplicationJSONString { get; set; }
        
        public string? GetConnectionInfo404ApplicationJSONString { get; set; }
        
        public string? GetConnectionInfo500ApplicationJSONString { get; set; }
        
        public int StatusCode { get; set; }
        
        public HttpResponseMessage? RawResponse { get; set; }
        
    }
}