
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora.Models.Lobby
{
    using Newtonsoft.Json;
    
    public enum CreateLobbyRequestBodyVisibility
    {
    	[JsonProperty("public")]
		Public,
		[JsonProperty("private")]
		Private,
		[JsonProperty("local")]
		Local,
    }
}