
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora.Models.Lobby
{
    using Hathora.Utils;
    using Hathora.Models.Shared;
    using NodaTime;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Net;
    using System.Net.Http;
    using System.Text;
    
public class DeprecatedV1CreatePrivateLobbyRequest
{
    [JsonProperty("appId")]
    public string AppId { get; set; }
    
    [JsonProperty("local")]
    public bool? Local { get; set; }
    
    [JsonProperty("region")]
    public Region? Region { get; set; }
    
    internal static HttpRequestMessage BuildHttpRequestMessage(string operationId, DeprecatedV1CreatePrivateLobbyRequest value, string baseUrl)
    {
        if("DeprecatedV1CreatePrivateLobby" == operationId)
        {
            var queryParams = new List<string>();
            
            
            queryParams.Add(QueryParamSerializer.Serialize("form",true, "local", "", value.Local));
            
            queryParams.Add(QueryParamSerializer.Serialize("form",true, "region", "", value.Region));
            var queryParamString = $"?{String.Join("&", queryParams)}";
            
            var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
            
            
            var message = new HttpRequestMessage(HttpMethod.Post, baseUrl + $"/lobby/v1/{appId}/create/private" + queryParamString);
            
            
            
            return message;
        }
        throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [DeprecatedV1CreatePrivateLobbyRequest]");
    }
}
}