
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora.Models.Lobby
{
    using System.Net.Http;
using Hathora.Models.Shared;
    
    public class DeprecatedCreateLocalLobbyResponse {
        public string? ContentType { get; set; }
        
        public string? DeprecatedCreateLocalLobby400ApplicationJSONString { get; set; }
        
        public string? DeprecatedCreateLocalLobby401ApplicationJSONString { get; set; }
        
        public string? DeprecatedCreateLocalLobby404ApplicationJSONString { get; set; }
        
        public string? DeprecatedCreateLocalLobby422ApplicationJSONString { get; set; }
        
        public string? DeprecatedCreateLocalLobby429ApplicationJSONString { get; set; }
        
        public string? DeprecatedCreateLocalLobby500ApplicationJSONString { get; set; }
        
        public Lobby? Lobby { get; set; }
        
        public int StatusCode { get; set; }
        
        public HttpResponseMessage? RawResponse { get; set; }
        
    }
}