
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Hathora.Models.Lobby
{
    using System.Net.Http;
    
    public class DeprecatedV1CreatePrivateLobbyResponse {
        public string? ContentType { get; set; }
        
        public string? DeprecatedV1CreatePrivateLobby400ApplicationJSONString { get; set; }
        
        public string? DeprecatedV1CreatePrivateLobby401ApplicationJSONString { get; set; }
        
        public string? DeprecatedV1CreatePrivateLobby404ApplicationJSONString { get; set; }
        
        public string? DeprecatedV1CreatePrivateLobby422ApplicationJSONString { get; set; }
        
        public string? DeprecatedV1CreatePrivateLobby429ApplicationJSONString { get; set; }
        
        public string? DeprecatedV1CreatePrivateLobby500ApplicationJSONString { get; set; }
        
    /// <summary>
    /// Ok
    /// </summary>
        public string? RoomId { get; set; }
        
        public int StatusCode { get; set; }
        
        public HttpResponseMessage? RawResponse { get; set; }
        
    }
}